# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


resources:
  repositories:
  - repository: mytest  # identifier (A-Z, a-z, 0-9, and underscore)
    type: github  # see the following "Type" topic
    name: Paprika-a11y/mytest  # repository name (format depends on `type`)
    ref: refs/heads/main  # ref name to use; defaults to 'refs/heads/main'
    endpoint: githubPAT  # name of the service connection to use (for types that aren't Azure Repos)
    trigger: none

pool:
  vmImage: windows-latest

steps:
- script: echo Hello world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
  displayName: 'Run a multi-line script2'
