# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



resources:
  repositories:
  - repository: mytest
    type: github
    name: Paprika-a11y/mytest
    ref: refs/heads/main
    endpoint: githubPAT
    trigger: 
    - main

trigger: 
- none

# pool:
#   vmImage: ubuntu-22.04

# jobs:
# - job: Job1
#   steps:
#     - checkout: none
#     - task: Bash@3
#       inputs:
#         targetType: 'inline'
#         script: |
#           sudo apt-get install flake8
#           sudo apt-get update

stages:
  - stage: buildDevelopment
    displayName: "build | development"
    jobs:
    - job: myjob
      displayName: "build development version"
      timeoutInMinutes: 60 # 1 hour
      pool:
        vmImage: 'windows-latest'
        steps:
        - checkout: none
        - script: echo "hello code"
