# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



resources:
  repositories:
  - repository: mytest
    type: github
    name: Paprika-a11y/mytest
    ref: refs/heads/main
    endpoint: githubPAT

trigger: 
- none

pool:
  vmImage: ubuntu-20.04

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get install flake8
      sudo apt-get update
